/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api-keys": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List API Keys */
    get: operations["list-api-keys"];
    put?: never;
    /**
     * Create API Key
     * @description Must be `admin` of the organization.
     */
    post: operations["create-api-key"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api-keys/{api-key}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get API Key */
    get: operations["get-api-key"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/organizations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Organizations */
    get: operations["list-organizations"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/organizations/{organization}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Organization */
    get: operations["get-organization"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/organizations/{organization}/join": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Join User
     * @description Join user to organization.
     *
     *     If you are `admin` in the organization, the `role` defaults to `member`.
     *     If not, you can only join the `demo-treasury` organization with its default role of `anon` (anonymous guest).
     */
    post: operations["join-user"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/organizations/{organization}/leave": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Leave User
     * @description Leave user from organization.
     *
     *     Must be `admin` in the organization, or leaving yourself.
     */
    post: operations["leave-user"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/treasuries": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Treasuries */
    get: operations["list-treasuries"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/treasuries/{treasury}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Treasury */
    get: operations["get-treasury"];
    /** Update Treasury */
    put: operations["update-treasury"];
    /** Create Treasury */
    post: operations["create-treasury"];
    /** Delete Treasury */
    delete: operations["delete-treasury"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/treasuries/{treasury}/nodes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Nodes */
    get: operations["get-nodes"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Users */
    get: operations["list-users"];
    put?: never;
    /**
     * Create User
     * @description Create a Cordial User account with an unknown password.
     *
     *     Must be `admin` in some existing Cordial Organization, to create a user for yourself, visit https://treasury.cordial.systems and sign up.
     */
    post: operations["create-user"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/{user}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get User */
    get: operations["get-user"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/{user}/anonymous": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get User Anonymization
     * @description `INOFFICIAL` Get a deterministic "random" anonymization of the user information. This is the same as what "anon" users would see about other "anon" users.
     *
     *     This is informational only and should not be used in production (simply use Get Us).
     */
    get: operations["get-user-anonymous"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/{user}/avatar": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get User Avatar
     * @description Get a deterministic "random" avatar for the user.
     */
    get: operations["get-user-avatar"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/{user}/extension": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Extension Config */
    get: operations["get-extension"];
    /**
     * Set Extension Config
     * @description CLI example: `treasury -P -t Pe3myB2GzNb2z6UhVUmak7 admin user extension set --origin https://orca.so --address chains/ETH/addresses/$RANDOM --address chains/SOL/addresses/$RANDOM`
     */
    put: operations["set-extension"];
    post?: never;
    /** Clear Extension Config */
    delete: operations["clear-extension"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/{user}/extension/poll": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Poll Extension Config
     * @description This is a "long poll", it returns once the configuration has changed.
     */
    get: operations["poll-extension"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** ApiKey */
    ApiKey: {
      name: components["schemas"]["ApiKeyName"];
    } & components["schemas"]["Metadata"] &
      components["schemas"]["ApiKeyData"];
    /** ApiKeyCreate */
    ApiKeyCreate: {
      description?: string;
      organization: components["schemas"]["OrganizationName"];
    };
    /** ApiKeyData */
    ApiKeyData: {
      /** @description This is set once only after creation.  The user will need to record it. */
      api_key?: string;
      description?: string;
      node?: components["schemas"]["NodeName"];
      organization: components["schemas"]["OrganizationName"];
      /** @description This is set only after creation. */
      secret?: string;
    };
    /** ApiKeyName */
    ApiKeyName: string;
    /** ApiKeyPage */
    ApiKeyPage: {
      "api-keys"?: components["schemas"]["ApiKeyName"][];
    } & components["schemas"]["Pagination"];
    /**
     * Bak
     * @example {
     *       "id": "cold",
     *       "bak": "age1cxukt95cfede6mmppvvx4tnrkcrw9sslkhwtumlw6xzdmzlml58shn2am6"
     *     }
     */
    Bak: {
      /** @description The age public key. */
      bak: string;
      /** @description Optional ID for the backup key. */
      id?: string;
    };
    /**
     * Email
     * @example john@doe.com
     */
    Email: string;
    /**
     * Error
     * @description API failure response, with HTTP error codes mapped from the gRPC error code as per https://github.com/googleapis/googleapis/blob/master/google/rpc/code.proto with the following adjustments:
     *
     *     - 1 Cancelled -> 400 Bad Request
     *     - 4 Deadline Exceeded -> 500 Internal Server Error
     *
     *     Note that a correct client should only consider 2xx (success) vs. 4xx or 5xx (failure), and then
     *     make decisions based on the `error.code` only.
     *
     *     In particular, `error.message` is informational and NOT stable.
     */
    Error: {
      code?: components["schemas"]["ErrorCode"];
      message?: string;
      status?: components["schemas"]["ErrorStatus"];
    };
    /**
     * ErrorCode
     * @description https://grpc.io/docs/guides/status-codes/
     */
    ErrorCode: number;
    /**
     * ErrorStatus
     * @description Human-readable version of the ErrorCode, informational only.
     */
    ErrorStatus: string;
    /**
     * Extension
     * @description Extension configuration
     */
    Extension: {
      config?: components["schemas"]["ExtensionConfig"];
      revision: string;
    };
    /** ExtensionConfig */
    ExtensionConfig: {
      addresses: string[];
      origins: string[];
      treasury: components["schemas"]["ExtensionTreasury"];
    };
    /** ExtensionTreasury */
    ExtensionTreasury: {
      name: string;
      url: string;
    };
    /** Invite */
    Invite: {
      /** @description The secret invite for the user to enroll into the Treasury. */
      code?: string;
      /** @description The user's ID on single sign on. */
      sso?: string;
      /** @description User ID on the treasury instance. */
      user?: string;
    };
    /** Keys */
    Keys: {
      engine: {
        identity: string;
      };
      node: {
        identity: string;
      };
      signer: {
        identity: string;
        recipient: string;
      };
    };
    /** Metadata */
    Metadata: {
      create_time: components["schemas"]["Timestamp"];
      creator: components["schemas"]["UserName"];
      update_time?: components["schemas"]["Timestamp"];
    };
    /** Node */
    Node: {
      name: components["schemas"]["NodeName"];
    } & components["schemas"]["Metadata"] &
      components["schemas"]["NodeData"];
    /** NodeData */
    NodeData: {
      baks?: components["schemas"]["Bak"][];
      connector: boolean;
      creator: string;
      description?: string;
      host: string;
      keys?: components["schemas"]["Keys"];
      port?: number;
      updater?: string;
    };
    /**
     * NodeName
     * @example treasuries/akiWPZUk9P8CFgsVoS4ce1/nodes/1
     */
    NodeName: string;
    /** NodePage */
    NodePage: {
      nodes?: components["schemas"]["Node"][];
    } & components["schemas"]["Pagination"];
    /** Organization */
    Organization: {
      name: components["schemas"]["OrganizationName"];
    } & components["schemas"]["Metadata"] &
      components["schemas"]["OrganizationData"];
    /**
     * OrganizationData
     * @example {
     *       "display_name": "Cordial Systems",
     *       "slug": "cordialsys",
     *       "private_metadata": {},
     *       "public_metadata": {},
     *       "users": {
     *         "users/2d3qy9rqnOgM1cdeQVxQowgU954": "admin",
     *         "users/2dXYl4b82imERSujQrDdcjorq7d": "member"
     *       }
     *     }
     */
    OrganizationData: {
      display_name?: string;
      /** @description `OUTPUT ONLY`. Keys are email domains, values signify if users with verified matching email domains may join the organization. */
      domains?: {
        [key: string]: boolean;
      };
      permissions?: components["schemas"]["Permission"][];
      slug?: string;
      /** @description `OUTPUT ONLY`. Keys are UserName, values are `admin` or `member`. */
      users?: {
        [key: string]: string;
      };
    };
    /**
     * OrganizationName
     * @example organizations/2d3s5YCcWatWNxpj80TO4R9TSuC
     */
    OrganizationName: string;
    /** OrganizationPage */
    OrganizationPage: {
      organizations?: components["schemas"]["Organization"][];
    } & components["schemas"]["Pagination"];
    /** Pagination */
    Pagination: {
      next_page_token?: string;
    };
    /**
     * Permission
     * @description An organization (or possibly individual user) may or may not have a given permission.
     * @constant
     */
    Permission: "full-access";
    /**
     * Role
     * @description User role in an organization.
     *
     *     - `admin` administers the organization
     *     - `member` general member
     *     - `anon` anonymous guest to the organization (use in `demo-treasury`)
     * @enum {string}
     */
    Role: "admin" | "anon" | "member";
    /**
     * Timestamp
     * @example {YYYY}-{MM}-{DD}T{HH}:{MM}:{SS}Z
     */
    Timestamp: string;
    /** Treasury */
    Treasury: {
      name: components["schemas"]["TreasuryName"];
    } & components["schemas"]["Metadata"] &
      components["schemas"]["TreasuryData"];
    /** TreasuryCreate */
    TreasuryCreate: {
      api?: string;
      description?: string;
      initial_version?: string;
      mainnet?: boolean;
      organization?: components["schemas"]["OrganizationName"];
      size?: number;
    };
    /** TreasuryData */
    TreasuryData: {
      api?: components["schemas"]["Url"];
      /** @description Optional, set of backup keys used when creating a `hosted` treasury. */
      baks?: components["schemas"]["Bak"][];
      description?: string;
      /** @description For hosted Treasuries, this is the ID of the enclave cluster that the treasury is hosted on. */
      host_id?: string;
      initial_version?: string;
      /** @description Output only once if the treasury is `hosted` and newly created. */
      invites?: components["schemas"]["Invite"][];
      network?: string;
      organization: components["schemas"]["OrganizationName"];
      size?: number;
      software?: string;
      variant: components["schemas"]["TreasuryVariant"];
    };
    /** TreasuryName */
    TreasuryName: string;
    /** TreasuryPage */
    TreasuryPage: {
      treasuries?: components["schemas"]["Treasury"][];
    } & components["schemas"]["Pagination"];
    /**
     * TreasuryVariant
     * @enum {string}
     */
    TreasuryVariant: "self-hosted" | "co-hosted" | "hosted";
    /**
     * Url
     * @description Valid URL
     */
    Url: string;
    /** User */
    User: {
      name: components["schemas"]["UserName"];
    } & components["schemas"]["Metadata"] &
      components["schemas"]["UserData"];
    /** UserData */
    UserData: {
      /** @description Concatenation of first and last name */
      display_name?: string;
      emails?: components["schemas"]["Email"][];
      first_name?: string;
      last_name?: string;
      /** @description `OUTPUT ONLY`. Keys are OrganizationName, values are `admin` or `member` */
      organizations?: {
        [key: string]: string;
      };
      primary_email?: components["schemas"]["Email"];
    };
    /**
     * UserName
     * @example users/2d3qy9rqnOgM1cdeQVxQowgU954
     */
    UserName: string;
    /** UserPage */
    UserPage: {
      users?: components["schemas"]["User"][];
    } & components["schemas"]["Pagination"];
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type ApiKey = components["schemas"]["ApiKey"];
export type ApiKeyCreate = components["schemas"]["ApiKeyCreate"];
export type ApiKeyData = components["schemas"]["ApiKeyData"];
export type ApiKeyName = components["schemas"]["ApiKeyName"];
export type ApiKeyPage = components["schemas"]["ApiKeyPage"];
export type Bak = components["schemas"]["Bak"];
export type Email = components["schemas"]["Email"];
export type Error = components["schemas"]["Error"];
export type ErrorCode = components["schemas"]["ErrorCode"];
export type ErrorStatus = components["schemas"]["ErrorStatus"];
export type Extension = components["schemas"]["Extension"];
export type ExtensionConfig = components["schemas"]["ExtensionConfig"];
export type ExtensionTreasury = components["schemas"]["ExtensionTreasury"];
export type Invite = components["schemas"]["Invite"];
export type Keys = components["schemas"]["Keys"];
export type Metadata = components["schemas"]["Metadata"];
export type Node = components["schemas"]["Node"];
export type NodeData = components["schemas"]["NodeData"];
export type NodeName = components["schemas"]["NodeName"];
export type NodePage = components["schemas"]["NodePage"];
export type Organization = components["schemas"]["Organization"];
export type OrganizationData = components["schemas"]["OrganizationData"];
export type OrganizationName = components["schemas"]["OrganizationName"];
export type OrganizationPage = components["schemas"]["OrganizationPage"];
export type Pagination = components["schemas"]["Pagination"];
export type Permission = components["schemas"]["Permission"];
export type Role = components["schemas"]["Role"];
export type Timestamp = components["schemas"]["Timestamp"];
export type Treasury = components["schemas"]["Treasury"];
export type TreasuryCreate = components["schemas"]["TreasuryCreate"];
export type TreasuryData = components["schemas"]["TreasuryData"];
export type TreasuryName = components["schemas"]["TreasuryName"];
export type TreasuryPage = components["schemas"]["TreasuryPage"];
export type TreasuryVariant = components["schemas"]["TreasuryVariant"];
export type Url = components["schemas"]["Url"];
export type User = components["schemas"]["User"];
export type UserData = components["schemas"]["UserData"];
export type UserName = components["schemas"]["UserName"];
export type UserPage = components["schemas"]["UserPage"];
export type $defs = Record<string, never>;
export interface operations {
  "list-api-keys": {
    parameters: {
      query?: {
        /** @description AIP-160 filter */
        filter?: string;
      };
      header?: {
        /** @description Optional comma separated list of organization IDs. Only resources in these organizations will be returned. */
        Organization?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiKeyPage"];
        };
      };
    };
  };
  "create-api-key": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["ApiKeyCreate"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiKey"];
        };
      };
    };
  };
  "get-api-key": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        "api-key": string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiKey"];
        };
      };
    };
  };
  "list-organizations": {
    parameters: {
      query?: {
        /** @description AIP-160 filter */
        filter?: string;
      };
      header?: {
        /** @description Optional comma separated list of organization IDs. Only resources in these organizations will be returned. */
        Organization?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrganizationPage"];
        };
      };
    };
  };
  "get-organization": {
    parameters: {
      query?: {
        /** @description fetch users */
        users?: boolean;
      };
      header?: never;
      path: {
        organization: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Organization"];
        };
      };
    };
  };
  "join-user": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        organization: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": {
          role?: components["schemas"]["Role"];
          user?: components["schemas"]["UserName"];
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Organization"];
        };
      };
      /** @description The organization was updated, but the DB did not update in time. */
      504: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  "leave-user": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        organization: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["UserName"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Organization"];
        };
      };
      /** @description The organization was updated, but the DB did not update in time. */
      504: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  "list-treasuries": {
    parameters: {
      query?: {
        /** @description AIP-160 filter */
        filter?: string;
      };
      header?: {
        /** @description Bear token */
        Authorization?: string;
        /** @description Optional comma separated list of organization IDs. Only resources in these organizations will be returned. */
        Organization?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TreasuryPage"];
        };
      };
    };
  };
  "get-treasury": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        treasury: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Treasury"];
        };
      };
    };
  };
  "update-treasury": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        treasury: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["Treasury"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Treasury"];
        };
      };
    };
  };
  "create-treasury": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        treasury: string;
      };
      cookie?: never;
    };
    /** @description The field `organzation` is required only for requests by users who are in multiple organizations, otherwise it is inferred. */
    requestBody?: {
      content: {
        "application/json": components["schemas"]["TreasuryCreate"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Treasury"];
        };
      };
    };
  };
  "delete-treasury": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        treasury: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  "get-nodes": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        treasury: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NodePage"];
        };
      };
    };
  };
  "list-users": {
    parameters: {
      query?: {
        /** @description AIP-160 filter */
        filter?: string;
      };
      header?: {
        /** @description Optional comma separated list of organization IDs. Only resources in these organizations will be returned. */
        Organization?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserPage"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  "create-user": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": {
          email?: string;
          first_name?: string;
          last_name?: string;
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
      /** @description The user was created, but the DB did not update in time. */
      504: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  "get-user": {
    parameters: {
      query?: {
        /** @description fetch organizations */
        organizations?: boolean;
      };
      header?: never;
      path: {
        user: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  "get-user-anonymous": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            display_name?: string;
            first_name?: string;
            last_name?: string;
            primary_email?: string;
          };
        };
      };
    };
  };
  "get-user-avatar": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description PNG format, 100x100 pixels */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  "get-extension": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Extension"];
        };
      };
    };
  };
  "set-extension": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["Extension"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Extension"];
        };
      };
    };
  };
  "clear-extension": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Extension"];
        };
      };
    };
  };
  "poll-extension": {
    parameters: {
      query: {
        /** @description last seen configuration revision */
        revision: string;
      };
      header?: never;
      path: {
        user: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Extension"];
        };
      };
    };
  };
}
