/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/users/{user}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get User */
    get: operations["get-user"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Users */
    get: operations["list-users"];
    put?: never;
    /**
     * Create User
     * @description Create a Cordial User account with an unknown password.
     *
     *     Must be `admin` in some existing Cordial Organization, to create a user for yourself, visit https://treasury.cordial.systems and sign up.
     */
    post: operations["create-user"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/treasuries": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Treasuries */
    get: operations["list-treasuries"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/treasuries/{treasury}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Treasury */
    get: operations["get-treasury"];
    /** Update Treasury */
    put: operations["update-treasury"];
    /** Create Treasury */
    post: operations["create-treasury"];
    /** Delete Treasury */
    delete: operations["delete-treasury"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/organizations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Organizations */
    get: operations["list-organizations"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/organizations/{organization}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Organization */
    get: operations["get-organization"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api-keys": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List API Keys */
    get: operations["list-api-keys"];
    put?: never;
    /**
     * Create API Key
     * @description Must be `admin` of the organization.
     */
    post: operations["create-api-key"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api-keys/{api-key}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get API Key */
    get: operations["get-api-key"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/treasuries/{treasury}/nodes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Nodes */
    get: operations["get-nodes"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/organizations/{organization}/join": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Join User
     * @description Join user to organization.
     *
     *     If you are `admin` in the organization, the `role` defaults to `member`.
     *     If not, you can only join the `demo-treasury` organization with its default role of `anon` (anonymous guest).
     */
    post: operations["join-user"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/organizations/{organization}/leave": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Leave User
     * @description Leave user from organization.
     *
     *     Must be `admin` in the organization, or leaving yourself.
     */
    post: operations["leave-user"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/{user}/anonymous": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get User Anonymization
     * @description `INOFFICIAL` Get a deterministic "random" anonymization of the user information. This is the same as what "anon" users would see about other "anon" users.
     *
     *     This is informational only and should not be used in production (simply use Get Us).
     */
    get: operations["get-user-anonymous"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/{user}/avatar": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get User Avatar
     * @description Get a deterministic "random" avatar for the user.
     */
    get: operations["get-user-avatar"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/{user}/extension": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Extension Config */
    get: operations["get-extension"];
    /**
     * Set Extension Config
     * @description CLI example: `treasury -P -t Pe3myB2GzNb2z6UhVUmak7 admin user extension set --origin https://orca.so --address chains/ETH/addresses/$RANDOM --address chains/SOL/addresses/$RANDOM`
     */
    put: operations["set-extension"];
    post?: never;
    /** Clear Extension Config */
    delete: operations["clear-extension"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/{user}/extension/poll": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Poll Extension Config
     * @description This is a "long poll", it returns once the configuration has changed.
     */
    get: operations["poll-extension"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** User */
    User: {
      name: components["schemas"]["UserName"];
    } & components["schemas"]["Metadata"] &
      components["schemas"]["UserData"];
    /**
     * UserName
     * @example users/2d3qy9rqnOgM1cdeQVxQowgU954
     */
    UserName: string;
    /** Metadata */
    Metadata: {
      creator: components["schemas"]["UserName"];
      create_time: components["schemas"]["Timestamp"];
      update_time?: components["schemas"]["Timestamp"];
    };
    /**
     * Timestamp
     * @example {YYYY}-{MM}-{DD}T{HH}:{MM}:{SS}Z
     */
    Timestamp: string;
    /** UserData */
    UserData: {
      first_name?: string;
      last_name?: string;
      /** @description Concatenation of first and last name */
      display_name?: string;
      primary_email?: components["schemas"]["Email"];
      emails?: components["schemas"]["Email"][];
      /** @description `OUTPUT ONLY`. Keys are OrganizationName, values are `admin` or `member` */
      organizations?: {
        [key: string]: string;
      };
    };
    /**
     * Email
     * @example john@doe.com
     */
    Email: string;
    /** UserPage */
    UserPage: {
      users?: components["schemas"]["User"][];
    } & components["schemas"]["Pagination"];
    /** Pagination */
    Pagination: {
      next_page_token?: string;
    };
    /**
     * Error
     * @description API failure response, with HTTP error codes mapped from the gRPC error code as per https://github.com/googleapis/googleapis/blob/master/google/rpc/code.proto with the following adjustments:
     *
     *     - 1 Cancelled -> 400 Bad Request
     *     - 4 Deadline Exceeded -> 500 Internal Server Error
     *
     *     Note that a correct client should only consider 2xx (success) vs. 4xx or 5xx (failure), and then
     *     make decisions based on the `error.code` only.
     *
     *     In particular, `error.message` is informational and NOT stable.
     */
    Error: {
      code?: components["schemas"]["ErrorCode"];
      status?: components["schemas"]["ErrorStatus"];
      message?: string;
    };
    /**
     * ErrorCode
     * @description https://grpc.io/docs/guides/status-codes/
     */
    ErrorCode: number;
    /**
     * ErrorStatus
     * @description Human-readable version of the ErrorCode, informational only.
     */
    ErrorStatus: string;
    /** TreasuryPage */
    TreasuryPage: {
      treasuries?: components["schemas"]["Treasury"][];
    } & components["schemas"]["Pagination"];
    /** Treasury */
    Treasury: {
      name: components["schemas"]["TreasuryName"];
    } & components["schemas"]["Metadata"] &
      components["schemas"]["TreasuryData"];
    /** TreasuryName */
    TreasuryName: string;
    /** TreasuryData */
    TreasuryData: {
      description?: string;
      organization: components["schemas"]["OrganizationName"];
      api?: components["schemas"]["Url"];
      initial_version?: string;
      size?: number;
      network?: string;
      software?: string;
    };
    /**
     * OrganizationName
     * @example organizations/2d3s5YCcWatWNxpj80TO4R9TSuC
     */
    OrganizationName: string;
    /**
     * Url
     * @description Valid URL
     */
    Url: string;
    /** TreasuryCreate */
    TreasuryCreate: {
      mainnet?: boolean;
      description?: string;
      organization?: components["schemas"]["OrganizationName"];
      api?: string;
      initial_version?: string;
      size?: number;
    };
    /** OrganizationPage */
    OrganizationPage: {
      organizations?: components["schemas"]["Organization"][];
    } & components["schemas"]["Pagination"];
    /** Organization */
    Organization: {
      name: components["schemas"]["OrganizationName"];
    } & components["schemas"]["Metadata"] &
      components["schemas"]["OrganizationData"];
    /**
     * OrganizationData
     * @example {
     *       "display_name": "Cordial Systems",
     *       "slug": "cordialsys",
     *       "private_metadata": {},
     *       "public_metadata": {},
     *       "users": {
     *         "users/2d3qy9rqnOgM1cdeQVxQowgU954": "admin",
     *         "users/2dXYl4b82imERSujQrDdcjorq7d": "member"
     *       }
     *     }
     */
    OrganizationData: {
      display_name?: string;
      slug?: string;
      /** @description `OUTPUT ONLY`. Keys are email domains, values signify if users with verified matching email domains may join the organization. */
      domains?: {
        [key: string]: boolean;
      };
      /** @description `OUTPUT ONLY`. Keys are UserName, values are `admin` or `member`. */
      users?: {
        [key: string]: string;
      };
      permissions?: components["schemas"]["Permission"][];
    };
    /**
     * Permission
     * @description An organization (or possibly individual user) may or may not have a given permission.
     * @constant
     */
    Permission: "full-access";
    /** ApiKeyPage */
    ApiKeyPage: {
      "api-keys"?: components["schemas"]["ApiKeyName"][];
    } & components["schemas"]["Pagination"];
    /** ApiKeyName */
    ApiKeyName: string;
    /** ApiKeyCreate */
    ApiKeyCreate: {
      description?: string;
      organization: components["schemas"]["OrganizationName"];
    };
    /** ApiKey */
    ApiKey: {
      name: components["schemas"]["ApiKeyName"];
    } & components["schemas"]["Metadata"] &
      components["schemas"]["ApiKeyData"];
    /** ApiKeyData */
    ApiKeyData: {
      description?: string;
      organization: components["schemas"]["OrganizationName"];
      /** @description This is set only after creation. */
      secret?: string;
      node?: components["schemas"]["NodeName"];
      /** @description This is set once only after creation.  The user will need to record it. */
      api_key?: string;
    };
    /**
     * NodeName
     * @example treasuries/akiWPZUk9P8CFgsVoS4ce1/nodes/1
     */
    NodeName: string;
    /** NodePage */
    NodePage: {
      nodes?: components["schemas"]["Node"][];
    } & components["schemas"]["Pagination"];
    /** Node */
    Node: {
      name: components["schemas"]["NodeName"];
    } & components["schemas"]["Metadata"] &
      components["schemas"]["NodeData"];
    /** NodeData */
    NodeData: {
      host: string;
      port?: number;
      baks?: components["schemas"]["Bak"][];
      description?: string;
      keys?: components["schemas"]["Keys"];
      creator: string;
      updater?: string;
      connector: boolean;
    };
    /**
     * Bak
     * @example {
     *       "id": "cold",
     *       "bak": "age1cxukt95cfede6mmppvvx4tnrkcrw9sslkhwtumlw6xzdmzlml58shn2am6"
     *     }
     */
    Bak: {
      /** @description Optional ID for the backup key. */
      id?: string;
      /** @description The age public key. */
      bak: string;
    };
    /** Keys */
    Keys: {
      node: {
        identity: string;
      };
      engine: {
        identity: string;
      };
      signer: {
        identity: string;
        recipient: string;
      };
    };
    /**
     * Role
     * @description User role in an organization.
     *
     *     - `admin` administers the organization
     *     - `member` general member
     *     - `anon` anonymous guest to the organization (use in `demo-treasury`)
     * @enum {string}
     */
    Role: "admin" | "anon" | "member";
    /**
     * Extension
     * @description Extension configuration
     */
    Extension: {
      revision: string;
      config?: components["schemas"]["ExtensionConfig"];
    };
    /** ExtensionConfig */
    ExtensionConfig: {
      addresses: string[];
      origins: string[];
      treasury: components["schemas"]["ExtensionTreasury"];
    };
    /** ExtensionTreasury */
    ExtensionTreasury: {
      name: string;
      url: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  "get-user": {
    parameters: {
      query?: {
        /** @description fetch organizations */
        organizations?: boolean;
      };
      header?: never;
      path: {
        user: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  "list-users": {
    parameters: {
      query?: {
        /** @description AIP-160 filter */
        filter?: string;
      };
      header?: {
        /** @description Optional comma separated list of organization IDs. Only resources in these organizations will be returned. */
        Organization?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserPage"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  "create-user": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": {
          email?: string;
          first_name?: string;
          last_name?: string;
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
      /** @description The user was created, but the DB did not update in time. */
      504: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  "list-treasuries": {
    parameters: {
      query?: {
        /** @description AIP-160 filter */
        filter?: string;
      };
      header?: {
        /** @description Optional comma separated list of organization IDs. Only resources in these organizations will be returned. */
        Organization?: string;
        /** @description Bear token */
        Authorization?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TreasuryPage"];
        };
      };
    };
  };
  "get-treasury": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        treasury: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Treasury"];
        };
      };
    };
  };
  "update-treasury": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        treasury: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["Treasury"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Treasury"];
        };
      };
    };
  };
  "create-treasury": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        treasury: string;
      };
      cookie?: never;
    };
    /** @description The field `organzation` is required only for requests by users who are in multiple organizations, otherwise it is inferred. */
    requestBody?: {
      content: {
        "application/json": components["schemas"]["TreasuryCreate"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Treasury"];
        };
      };
    };
  };
  "delete-treasury": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        treasury: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  "list-organizations": {
    parameters: {
      query?: {
        /** @description AIP-160 filter */
        filter?: string;
      };
      header?: {
        /** @description Optional comma separated list of organization IDs. Only resources in these organizations will be returned. */
        Organization?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrganizationPage"];
        };
      };
    };
  };
  "get-organization": {
    parameters: {
      query?: {
        /** @description fetch users */
        users?: boolean;
      };
      header?: never;
      path: {
        organization: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Organization"];
        };
      };
    };
  };
  "list-api-keys": {
    parameters: {
      query?: {
        /** @description AIP-160 filter */
        filter?: string;
      };
      header?: {
        /** @description Optional comma separated list of organization IDs. Only resources in these organizations will be returned. */
        Organization?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiKeyPage"];
        };
      };
    };
  };
  "create-api-key": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["ApiKeyCreate"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiKey"];
        };
      };
    };
  };
  "get-api-key": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        "api-key": string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiKey"];
        };
      };
    };
  };
  "get-nodes": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        treasury: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NodePage"];
        };
      };
    };
  };
  "join-user": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        organization: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": {
          user?: components["schemas"]["UserName"];
          role?: components["schemas"]["Role"];
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Organization"];
        };
      };
      /** @description The organization was updated, but the DB did not update in time. */
      504: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  "leave-user": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        organization: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["UserName"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Organization"];
        };
      };
      /** @description The organization was updated, but the DB did not update in time. */
      504: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  "get-user-anonymous": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            first_name?: string;
            last_name?: string;
            display_name?: string;
            primary_email?: string;
          };
        };
      };
    };
  };
  "get-user-avatar": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description PNG format, 100x100 pixels */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  "get-extension": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Extension"];
        };
      };
    };
  };
  "set-extension": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["Extension"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Extension"];
        };
      };
    };
  };
  "clear-extension": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Extension"];
        };
      };
    };
  };
  "poll-extension": {
    parameters: {
      query: {
        /** @description last seen configuration revision */
        revision: string;
      };
      header?: never;
      path: {
        user: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Extension"];
        };
      };
    };
  };
}
