/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/assets": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Assets
     * @description List all the assets tracked by Oracle
     */
    get: operations["list-assets"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/assets/prices": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * DEPRECATED: List Asset Prices
     * @deprecated
     * @description Deprecated - migrate to the `price` field in the Asset endpoints.
     *
     *     Retrieves USD pricing on assets.
     */
    get: operations["list-asset-prices"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/chains/{chain}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Chain */
    get: operations["get-chain"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/chains/{chain}/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Chain Status
     * @description Check the health of chain and it's indexer state.  The JSON content is not API stable. Please use HTTP status (e.g. 200) for machine logic.
     */
    get: operations["get-chain-status"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/chains": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Chains
     * @description List all chains supported by the service.
     */
    get: operations["list-chains"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/addresses": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Addresses
     * @description Lists all the addresses the user is subscribed to.
     */
    get: operations["list-addresses"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/chains/{chain}/addresses": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Chain Addresses
     * @description Lists all the addresses on the specific chain the user is subscribed to.
     */
    get: operations["list-chain-addresses"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/chains/{chain}/addresses/{address}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Address */
    get: operations["get-address"];
    /**
     * Subscribe Address
     * @description Subscribe for balance and transaction data on a given address.
     *
     *     If the "normalization" of an address mangles it, set the `address` field.
     *     It is otherwise optional.
     *
     *     If an address subscription is older than 30 days, then it may be deleted automatically.
     *     You can subscribe addresses periodically to avoid this.
     */
    put: operations["subscribe-address"];
    post?: never;
    /**
     * Unsubscribe Address
     * @description Unsubscribes the user from the specified address.
     *
     *     This does not recursively remove the transaction data created so far.
     */
    delete: operations["delete-address"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/balances": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Balances
     * @description List all balances for addresses that have been subscribed to.
     */
    get: operations["list-balances"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/chains/{chain}/balances": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Chain Balances
     * @description List all balances for addresses that have been subscribed to on a given chain.
     */
    get: operations["list-chain-balances"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/chains/{chain}/addresses/{address}/balances": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Address Balances
     * @description Lists all the balances for an address that has been subscribed to.
     */
    get: operations["list-address-balances"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/chains/{chain}/addresses/{address}/balances/{asset}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Balance */
    get: operations["get-balance"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/chains/{chain}/transactions/{hash}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Transaction
     * @description Returns full transaction information, as can be seen from connector API.
     */
    get: operations["get-transaction"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/chains/{chain}/transactions/{hash}/index": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Index Transaction
     * @description This will manually index a transaction using only the hash.
     *     If the transaction is found, and it has at least one address that you are subscribed to, it will be created or updated.
     */
    post: operations["index-transaction"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/chains/{chain}/addresses/{address}/transactions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Address Transactions
     * @description Lists transactions related to the address in descending order by block time.
     */
    get: operations["list-address-transactions"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/chains/{chain}/assets/{asset}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Asset */
    get: operations["get-asset"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/transactions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Transactions
     * @description List all transactions, in descending order of the mined block time.
     */
    get: operations["list-transactions"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/deposits": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Deposits
     * @description List all deposits, in descending order of the mined block time.
     */
    get: operations["list-deposits"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/chains/{chain}/transactions/{hash}/movements/{movement}/deposits/{deposit}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Deposit */
    get: operations["get-deposit"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/chains/{chain}/addresses/{address}/deposits": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Address Deposits */
    get: operations["list-address-deposits"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/withdrawals": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Withdrawals */
    get: operations["list-withdrawals"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/chains/{chain}/addresses/{address}/withdrawals": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Address Withdrawals */
    get: operations["list-address-withdrawals"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/chains/{chain}/transactions/{hash}/movements/{movement}/withdrawals/{withdrawal}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Withdrawal */
    get: operations["get-withdrawal"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/movements": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Movements */
    get: operations["list-movements"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/chains/{chain}/addresses/{address}/movements": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Address Movements */
    get: operations["list-address-movements"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/chains/{chain}/transactions/{hash}/movements/{movement}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Movement */
    get: operations["get-movement"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/ws/{stream}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Subscribe to a WebSocket stream
     * @description ## WebSocket Endpoint for Transaction Updates
     *     <span style="display:inline-block;padding:0.25rem 0.5rem;border-radius:999px;font-weight:700;background:#FDE68A;color:#7C2D12;font-size:1rem">
     *       BETA
     *     </span>
     *
     *     This WebSocket endpoint allows clients to subscribe to real-time updates for **Deposits**, **Withdrawals**, or **Movements**. Updates are triggered whenever a **Transaction** resource is updated in Oracle.
     *
     *     **Important Considerations:**
     *     - **Duplicate Messages**: Updates may be sent multiple times for the same transaction. Client behavior is expected to be to be idempotent.
     *     - **Disconnections**: Clients are expected to be able to reconnect, and to use normal queries to backfill the last 5-10 minutes of activity. At a later time we may support automatic 10 minute backfills upon connection.
     *     **Subscription Rules:**
     *     Each WebSocket connection can subscribe to only one of the following streams at a time:
     *     - deposits
     *     - withdrawals
     *     - movements
     */
    get: operations["get-ws-stream"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AssetPage */
    AssetPage: {
      assets?: components["schemas"]["Asset"][];
    } & components["schemas"]["Pagination"];
    /** Asset */
    Asset: {
      name?: components["schemas"]["AssetName"];
    } & components["schemas"]["AssetData"];
    /**
     * AssetName
     * @example chains/MATIC/assets/MATIC
     */
    AssetName: string;
    /** AssetData */
    AssetData: {
      chain_id: string;
      id: string;
      decimals: number;
      price?: components["schemas"]["Price"];
      symbol?: string;
      ids?: components["schemas"]["Ids"];
      names?: components["schemas"]["Names"];
      prices?: components["schemas"]["Prices"];
      symbols?: components["schemas"]["Symbols"];
    };
    /** Price */
    Price: {
      time: components["schemas"]["Timestamp"];
      usd: components["schemas"]["Amount"];
    };
    /**
     * Timestamp
     * @description Seconds since UNIX epoch, encoded as UTC timestamp (ending in Z).
     * @example 2023-07-30T011:30:15Z
     */
    Timestamp: string;
    /**
     * Amount
     * @description Asset amount as decimal, encoded as string.
     * @example 2.13
     */
    Amount: string;
    /**
     * Ids
     * @description Identifiers assigned to chains or assets by external systems.
     */
    Ids: {
      coingecko?: string;
      coinmarketcap?: number;
      /** @description From "Header", "DTI" */
      dti?: string;
      /** @description From "UnderlyingAssetExternalIdentifiers", "UnderlyingAssetExternalIdentifierValue" where "UnderlyingAssetExternalIdentifierType" is "ISIN" */
      isin?: string;
    };
    /** Names */
    Names: {
      coingecko?: string;
      coinmarketcap?: string;
      /** @description From "Informative", "LongName" */
      dti?: string;
    };
    /** Prices */
    Prices: {
      coinmarketcap?: components["schemas"]["Price"];
      coingecko?: components["schemas"]["Price"];
    };
    /**
     * Symbols
     * @description Symbols assigned to chains or assets by external systems.
     */
    Symbols: {
      coingecko?: string;
      coinmarketcap?: string;
      /** @description From "Informative", "ShortName" */
      dti?: string;
    };
    /** Pagination */
    Pagination: {
      /** @description `OPTIONAL`. If set, there are more pages, which can be requested by repeating the `List` request, setting this value as query parameter `page_token`. */
      next_page_token?: string;
    };
    /** DeprecatedPrice */
    DeprecatedPrice: {
      asset_name?: components["schemas"]["AssetName"];
      price?: number;
      update_time?: components["schemas"]["Timestamp"];
    };
    /** Chain */
    Chain: {
      name: components["schemas"]["ChainName"];
    } & components["schemas"]["ChainData"];
    /** ChainName */
    ChainName: string;
    /**
     * ChainData
     * @example {
     *       "id": "ETH",
     *       "network": "mainnet"
     *     }
     * @example {
     *       "id": "SOL",
     *       "network": "devnet"
     *     }
     */
    ChainData: {
      id?: string;
      network?: string;
    };
    /**
     * ChainStatus
     * @description Returns metadata about the health of a chain.  Note this type is not API stable.  Please use HTTP status (e.g. 200) for machine logic.
     */
    ChainStatus: {
      chain?: components["schemas"]["ChainName"];
      ok?: boolean;
      /** @description Last time this was updated. */
      update_time?: components["schemas"]["Timestamp"];
      rpc?: {
        ok?: boolean;
        message?: string;
        /** @description The latest block height, as observable on RPC. */
        block_height?: number;
      };
      indexer?: {
        ok?: boolean;
        message?: string;
        /** @description If known, this will be set to the latest height that the indexer has processed. */
        block_height?: number;
      };
      queue?: {
        ok?: boolean;
        message?: string;
        /** @description The current size of transaction queue to index. */
        size?: number;
      };
    };
    /** ChainPage */
    ChainPage: {
      chains?: components["schemas"]["Chain"][];
    } & components["schemas"]["Pagination"];
    /** AddressPage */
    AddressPage: {
      addresses: components["schemas"]["Address"][];
    } & components["schemas"]["Pagination"];
    /** Address */
    Address: {
      /** @description `OUTPUT ONLY` */
      name: components["schemas"]["AddressName"];
    } & components["schemas"]["AddressData"] &
      components["schemas"]["Metadata"];
    /**
     * AddressName
     * @description The name of an address consists of its parent chain name and the normalization of its on-chain representation as `Id`.
     * @example chains/SOL/addresses/2mp7kgAGSUXMRPVtpJQxQwXpUw7UAhYjh2gjYeCL5zsMeL1VMKidcfeY5J1BptDtoAyb24U58qCGCe8QVui8Yz5x
     */
    AddressName: string;
    /**
     * AddressData
     * @example {
     *       "chain_id": "ETH",
     *       "id": "0xced92fa7f0797cbc851b48140ae218a0b0d41ce0",
     *       "subscribe_time": "2023-07-30T011:30:15Z",
     *       "address": "string"
     *     }
     */
    AddressData: {
      chain_id: string;
      id: string;
      subscribe_time: components["schemas"]["Timestamp"];
      /** @description Unnormalized version of the address ID. */
      address?: string;
      /** @description The treasury that this address is associated with, e.g. `SGxCSBhhjdJ1LAGBSeAM5i`.  This will be set if the `TREASURY` header is set when creating the address. */
      treasury_id?: string;
      /** @description The address variant, e.g. `internal`. */
      variant?: string;
      /** @description Logically account that the address may be in. */
      account_id?: string;
      description?: string;
    };
    /** Metadata */
    Metadata: {
      create_time: components["schemas"]["Timestamp"];
      update_time?: components["schemas"]["Timestamp"];
    };
    /** AddressBalancesPage */
    AddressBalancesPage: {
      balances?: components["schemas"]["AddressBalance"][];
    } & components["schemas"]["Pagination"];
    /** AddressBalance */
    AddressBalance: {
      name: components["schemas"]["AddressBalanceName"];
    } & components["schemas"]["Metadata"] &
      components["schemas"]["AddressBalanceData"];
    /**
     * AddressBalanceName
     * @example chains/ETH/addresses/0xced92fa7f0797cbc851b48140ae218a0b0d41ce0/balances/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48
     */
    AddressBalanceName: string;
    /** AddressBalanceData */
    AddressBalanceData: {
      address_id: string;
      asset_id: string;
      amount?: components["schemas"]["Amount"];
      balance: components["schemas"]["Balance"];
      address?: string;
      contract?: string;
    };
    /**
     * Balance
     * @description Base units of an asset as an integer (not adjusted for decimals), encoded as string.
     * @example 213213432
     */
    Balance: string;
    /**
     * Transaction
     * @description This is the same model as from the connector API.
     */
    Transaction: {
      name?: components["schemas"]["TransactionName"];
    } & components["schemas"]["Metadata"] &
      components["schemas"]["TransactionData"];
    /**
     * TransactionName
     * @description The name of an transactions consists of its (parent) chain name, its on-chain identifier (usually the 'transaction hash').
     * @example chains/MATIC/transactions/0x4a0f7a74ba1824504ac7f0dd462e2b287226691828d04fee66cff42aaa6756db
     */
    TransactionName: string;
    /** TransactionData */
    TransactionData: {
      block: components["schemas"]["Block"];
      /** @description The transaction's hash. */
      id: string;
      fees: components["schemas"]["Fee"][];
      movements: components["schemas"]["MovementCore"][];
      confirmations: number;
      /** @description If there was an issue with the transaction, this field will be set. The transaction nevertheless occurred, and the credits and debits were applied, typically just fees. */
      error?: string;
      /** @description `OUTPUT ONLY`. The transaction's hash. */
      hash?: string;
      state?: components["schemas"]["TransactionState"];
      /** @description If the `confirmations` is high enough for this transaction to be considered "final" on the chain, this will be true. */
      final?: boolean;
      /** @description Cordial Systems identifier for the chain. */
      chain_id: string;
    };
    /**
     * Block
     * @example {
     *       "chain_id": "ETH",
     *       "id": "0x5e02e3762b09328a3b90f9b8f1caa38c79385bc704fd936173d36cf11bdd88b9",
     *       "height": 21115105,
     *       "time": "2023-07-30T011:30:15Z",
     *       "chain": "chains/ETH",
     *       "hash": "0x5e02e3762b09328a3b90f9b8f1caa38c79385bc704fd936173d36cf11bdd88b9"
     *     }
     */
    Block: {
      /** @description Cordial Systems identifier for the chain. */
      chain_id: string;
      /** @description The block's hash */
      id?: string;
      height?: number;
      time?: components["schemas"]["Timestamp"];
      hash?: string;
    };
    /**
     * Fee
     * @description An amount taken for fees.
     */
    Fee: {
      asset_id: string;
      /** @description If decimals for asset are available, `balance` field scaled by `decimals` to decimal `Amount`. */
      amount?: components["schemas"]["Amount"];
      /** @description The balance of `asset` sent or received by `address`. */
      balance: components["schemas"]["Balance"];
      /** @description The asset being transferred. */
      asset?: components["schemas"]["AssetName"];
      contract?: string;
    };
    /** MovementCore */
    MovementCore: {
      asset_id: string;
      /** @description Index `>=1` of movement within parent transaction */
      id: number;
      to: components["schemas"]["AmountChange"][];
      from: components["schemas"]["AmountChange"][];
      asset?: components["schemas"]["AssetName"];
      contract?: string;
    };
    /**
     * AmountChange
     * @description Change in amount for an address that contributes to a given movement.
     */
    AmountChange: {
      address_id: string;
      amount?: components["schemas"]["Amount"];
      /** @description The balance of `asset` sent or received by `address`. */
      balance: components["schemas"]["Balance"];
      /** @description Address that contributed funds to this movement. */
      address?: components["schemas"]["AddressName"];
      subscribed?: boolean;
      event?: components["schemas"]["Event"];
    };
    /**
     * Event
     * @description Reference to an on-chain event or log within the transaction.
     *
     *
     *     ### Aptos
     *
     *     Events use the index of the event list in the Aptos transaction.
     *
     *     ```json
     *     {"variant": "native", "id": "1"}
     *     ```
     *
     *     ### Bitcoin
     *
     *     Balance changes (not the movement) are mapped to UTXO.
     *
     *     ```json
     *     {"variant": "native", "id": "2bdfcbd40ac3242c5da665ea41a4eef36445d01c526966b7788b23d618598b46:1"}
     *     ```
     *
     *     ### Cosmos
     *
     *     Events use the index of the event list in the Cosmos transaction.
     *
     *     ```json
     *     {"variant": "native", "id": "1"}
     *     ```
     *
     *     ### Solana
     *
     *     Uses the instruction number (starting at 1), as shown on block explorers.
     *
     *     ```json
     *     {"variant": "native", "id": "1"}
     *     ```
     *
     *     #### Inner instructions
     *
     *     Solana "inner" instructions will also match the explorer.
     *
     *     ```json
     *     {"variant": "native", "id": "3.1"}
     *     ```
     *
     *     ### EVM
     *
     *     #### Normal ether transfer
     *
     *     Maps to the value field of the transaction.
     *
     *     ```json
     *     {"variant": "native", "id": ""}
     *     ```
     *
     *     #### Normal token transfer
     *
     *     Maps to the log index.
     *
     *     ```json
     *     {"variant": "token", "id": "42"}
     *     ```
     *
     *     #### Internal ether transfer
     *
     *     Maps to the trace address of `trace_transaction` RPC (`traceAddress.join("_")`).
     *
     *     ```json
     *     {"variant": "internal", "id": "0_0_1"}
     *     ```
     *
     *     ### SUI
     *
     *     SUI events are indexed from the list of balance changes.
     *     These map to the balance-changes in the movement.
     *
     *     ```json
     *     {"variant": "native", "id": "1"}
     *     ```
     * @example {
     *       "id": "42",
     *       "variant": "token"
     *     }
     * @example {
     *       "id": "0_0_1",
     *       "variant": "internal"
     *     }
     * @example {
     *       "id": "",
     *       "variant": "native"
     *     }
     * @example {
     *       "id": "",
     *       "variant": "fee"
     *     }
     * @example {
     *       "id": "544ead59208f1f425f31eaded743f68e95c100ddcb5eb329bcba188a93d3da25:5",
     *       "variant": "native"
     *     }
     */
    Event: {
      id: string;
      variant: components["schemas"]["EventVariant"];
    };
    /**
     * EventVariant
     * @description If the transaction has multiple types of events or logs, this variant will map to the particular event log of the transaction.
     *
     *     For example, EVM chains have the `internal` trace log, the `token` log, and the `native` ether transfer.
     *
     *     Most chains have a single, consistent log and will just use `native` or `fee` variants.
     * @enum {string}
     */
    EventVariant: "native" | "token" | "internal" | "fee";
    /**
     * TransactionState
     * @description **mining**: The transaction is not yet confirmed by any miner or validator on the network (in the "mempool").
     *
     *     **succeeded** The transaction is validated by at least one validator or miner (in a "block").
     *
     *     **failed** The transaction failed or reverted.  The network refused to persist the transaction's changes, but the sender paid fees.
     * @enum {string}
     */
    TransactionState: "mining" | "succeeded" | "failed";
    AddressTransactionPage: {
      address?: components["schemas"]["AddressName"];
      transactions?: components["schemas"]["Transaction"][];
    } & components["schemas"]["Pagination"];
    /** TransactionPage */
    TransactionPage: {
      transactions?: components["schemas"]["Transaction"][];
    } & components["schemas"]["Pagination"];
    /** DepositPage */
    DepositPage: {
      deposits?: components["schemas"]["Deposit"][];
    } & components["schemas"]["Pagination"];
    /** Deposit */
    Deposit: {
      name?: components["schemas"]["DepositName"];
    } & components["schemas"]["Metadata"] &
      components["schemas"]["DepositData"];
    /**
     * DepositName
     * @example chains/SOL/transactions/0xd2d6e66eca10af3db7ac50c48b6c8f9863657d1581f78f11e544c4254553f9f6/movements/1/deposits/1
     */
    DepositName: string;
    /** DepositData */
    DepositData: {
      block: components["schemas"]["Block"];
      transaction_id: string;
      movement_id: number;
      /** @description Index `>=1` of deposit within parent movement. */
      id: number;
      /** @description The unmodified version of contract in `asset`. */
      asset_id: string;
      /** @description Asset amount as decimal, encoded as string.  This is only set if the *decimals* is known for the asset. */
      amount?: components["schemas"]["Amount"];
      balance: components["schemas"]["Balance"];
      /** @description Address(es) that contributed to sending of this asset */
      from_ids?: string[];
      /** @description The address that received the asset. */
      to_id: string;
      confirmations: number;
      error?: string;
      state?: components["schemas"]["TransactionState"];
      /** @description If the `confirmations` is high enough for this transaction to be considered "final" on the chain, this will be true. */
      final?: boolean;
      event?: components["schemas"]["Event"];
      memo?: string;
    };
    /** WithdrawalPage */
    WithdrawalPage: {
      withdrawals?: components["schemas"]["Withdrawal"][];
    } & components["schemas"]["Pagination"];
    /** Withdrawal */
    Withdrawal: {
      name?: components["schemas"]["WithdrawalName"];
    } & components["schemas"]["Metadata"] &
      components["schemas"]["WithdrawalData"];
    /**
     * WithdrawalName
     * @example chains/ETH/transactions/0xd2d6e66eca10af3db7ac50c48b6c8f9863657d1581f78f11e544c4254553f9f6/movements/1/withdrawals/1
     */
    WithdrawalName: string;
    /** WithdrawalData */
    WithdrawalData: {
      block: components["schemas"]["Block"];
      transaction_id: string;
      movement_id: number;
      /** @description Index `>=1` of withdrawal within parent movement. */
      id: number;
      asset_id: string;
      /** @description Asset amount as decimal, encoded as string.  This is only set if the *decimals* is known for the asset. */
      amount?: components["schemas"]["Amount"];
      balance?: components["schemas"]["Balance"];
      /** @description The address that sent the asset. */
      from_id: string;
      /** @description The address(es) that have received at least some of this asset. */
      to_ids?: string[];
      confirmations: number;
      error?: string;
      state?: components["schemas"]["TransactionState"];
      /** @description If the `confirmations` is high enough for this transaction to be considered "final" on the chain, this will be true. */
      final?: boolean;
      event?: components["schemas"]["Event"];
      memo?: string;
    };
    /** MovementPage */
    MovementPage: {
      movements?: components["schemas"]["Movement"][];
    } & components["schemas"]["Pagination"];
    /** Movement */
    Movement: {
      name?: components["schemas"]["MovementName"];
    } & components["schemas"]["Metadata"] &
      components["schemas"]["MovementData"];
    /**
     * MovementName
     * @example chains/SOL/transactions/0xd2d6e66eca10af3db7ac50c48b6c8f9863657d1581f78f11e544c4254553f9f6/movements/1
     */
    MovementName: string;
    /**
     * MovementData
     * @example {
     *       "asset_id": "MATIC",
     *       "from": [
     *         {
     *           "balance": "2222222",
     *           "address_id": "0x732134d7f99b90c704d736b360db45425073380f"
     *         },
     *         {
     *           "balance": "1000000000",
     *           "address_id": "0x732134d7f99b90c704d736b360db45425073380f"
     *         }
     *       ],
     *       "to": [
     *         {
     *           "balance": "1000000000",
     *           "address_id": "0xedf073581267d82b6e4fd63b5fb288f1876555cd"
     *         }
     *       ]
     *     }
     */
    MovementData: {
      block: components["schemas"]["Block"];
      transaction_id: string;
    } & components["schemas"]["MovementCore"] & {
        confirmations: number;
        error?: string;
      } & {
        state?: components["schemas"]["TransactionState"];
        /** @description If the `confirmations` is high enough for this transaction to be considered "final" on the chain, this will be true. */
        final?: boolean;
        event?: components["schemas"]["Event"];
        memo?: string;
      };
  };
  responses: never;
  parameters: {
    filter: string;
    /** @description Pagination token returned from the previous request */
    page_token: string;
    /** @description Amount of elements to return per page */
    page_size: number;
    order_by: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  "list-assets": {
    parameters: {
      query?: {
        /** @description Amount of elements to return per page */
        page_size?: components["parameters"]["page_size"];
        /** @description Pagination token returned from the previous request */
        page_token?: components["parameters"]["page_token"];
        filter?: components["parameters"]["filter"];
        order_by?: components["parameters"]["order_by"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AssetPage"];
        };
      };
    };
  };
  "list-asset-prices": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DeprecatedPrice"][];
        };
      };
    };
  };
  "get-chain": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        chain: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Chain"];
        };
      };
    };
  };
  "get-chain-status": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        chain: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChainStatus"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChainStatus"];
        };
      };
    };
  };
  "list-chains": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChainPage"];
        };
      };
    };
  };
  "list-addresses": {
    parameters: {
      query?: {
        /** @description Amount of elements to return per page */
        page_size?: components["parameters"]["page_size"];
        /** @description Pagination token returned from the previous request */
        page_token?: components["parameters"]["page_token"];
        filter?: components["parameters"]["filter"];
        order_by?: components["parameters"]["order_by"];
      };
      header: {
        /** @description Requester's identity */
        Organization: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "*/*"?: never;
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AddressPage"];
        };
      };
    };
  };
  "list-chain-addresses": {
    parameters: {
      query?: {
        filter?: components["parameters"]["filter"];
        order_by?: components["parameters"]["order_by"];
        /** @description Pagination token returned from the previous request */
        page_token?: components["parameters"]["page_token"];
        /** @description Amount of elements to return per page */
        page_size?: components["parameters"]["page_size"];
      };
      header: {
        /** @description Requester's identity */
        Organization: string;
      };
      path: {
        chain: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AddressPage"];
        };
      };
    };
  };
  "get-address": {
    parameters: {
      query?: never;
      header: {
        /** @description Requester's identity */
        Organization: string;
      };
      path: {
        address: string;
        chain: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      "2XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Address"];
        };
      };
    };
  };
  "subscribe-address": {
    parameters: {
      query?: never;
      header: {
        /** @description Requester's identity */
        Organization: string;
      };
      path: {
        address: string;
        chain: string;
      };
      cookie?: never;
    };
    /**
     * @description Subscribes the organization to the specified address.
     *
     *     Creating an address puts it on the oracle's watchlist, it will backfill and start adding transactions as they occur.
     */
    requestBody?: {
      content: {
        "application/json": components["schemas"]["Address"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/plain": string;
        };
      };
    };
  };
  "delete-address": {
    parameters: {
      query?: never;
      header: {
        /** @description Requester's identity */
        Organization: string;
      };
      path: {
        address: string;
        chain: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  "list-balances": {
    parameters: {
      query?: {
        /** @description Pagination token returned from the previous request */
        page_token?: components["parameters"]["page_token"];
        /** @description Amount of elements to return per page */
        page_size?: components["parameters"]["page_size"];
        filter?: components["parameters"]["filter"];
        order_by?: components["parameters"]["order_by"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AddressBalancesPage"];
        };
      };
    };
  };
  "list-chain-balances": {
    parameters: {
      query?: {
        /** @description Pagination token returned from the previous request */
        page_token?: components["parameters"]["page_token"];
        /** @description Amount of elements to return per page */
        page_size?: components["parameters"]["page_size"];
        filter?: components["parameters"]["filter"];
        order_by?: components["parameters"]["order_by"];
      };
      header?: never;
      path: {
        chain: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AddressBalancesPage"];
        };
      };
    };
  };
  "list-address-balances": {
    parameters: {
      query?: {
        /** @description Amount of elements to return per page */
        page_size?: components["parameters"]["page_size"];
        /** @description Pagination token returned from the previous request */
        page_token?: components["parameters"]["page_token"];
        filter?: components["parameters"]["filter"];
        order_by?: components["parameters"]["order_by"];
      };
      header: {
        /** @description Requester's identity */
        Organization: string;
      };
      path: {
        chain: string;
        address: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AddressBalancesPage"];
        };
      };
    };
  };
  "get-balance": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        chain: string;
        address: string;
        asset: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AddressBalance"];
        };
      };
    };
  };
  "get-transaction": {
    parameters: {
      query?: never;
      header: {
        /** @description Requester's identity */
        Organization: string;
      };
      path: {
        /** @description Chain of the transaction */
        chain: string;
        hash: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Transaction"];
        };
      };
    };
  };
  "index-transaction": {
    parameters: {
      query?: {
        /** @description Set to update the address subscription if needed.  This may cause other old transactions to get reported. */
        update_subscription?: unknown;
      };
      header: {
        /** @description Requester's identity */
        Organization: string;
      };
      path: {
        /** @description Chain of the transaction */
        chain: string;
        /** @description Transaction ID */
        hash: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Transaction"];
        };
      };
    };
  };
  "list-address-transactions": {
    parameters: {
      query?: {
        /** @description Pagination token returned from the previous request */
        page_token?: components["parameters"]["page_token"];
        /** @description Amount of elements to return per page */
        page_size?: components["parameters"]["page_size"];
        order_by?: components["parameters"]["order_by"];
        filter?: components["parameters"]["filter"];
      };
      header?: never;
      path: {
        chain: string;
        address: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AddressTransactionPage"];
        };
      };
    };
  };
  "get-asset": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        chain: string;
        asset: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Asset"];
        };
      };
    };
  };
  "list-transactions": {
    parameters: {
      query?: {
        /** @description Pagination token returned from the previous request */
        page_token?: components["parameters"]["page_token"];
        /** @description Amount of elements to return per page */
        page_size?: components["parameters"]["page_size"];
        filter?: components["parameters"]["filter"];
        order_by?: components["parameters"]["order_by"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TransactionPage"];
        };
      };
    };
  };
  "list-deposits": {
    parameters: {
      query?: {
        /** @description Amount of elements to return per page */
        page_size?: components["parameters"]["page_size"];
        /** @description Pagination token returned from the previous request */
        page_token?: components["parameters"]["page_token"];
        order_by?: components["parameters"]["order_by"];
        filter?: components["parameters"]["filter"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DepositPage"];
        };
      };
    };
  };
  "get-deposit": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        chain: string;
        hash: string;
        movement: string;
        deposit: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Deposit"];
        };
      };
    };
  };
  "list-address-deposits": {
    parameters: {
      query?: {
        /** @description Amount of elements to return per page */
        page_size?: components["parameters"]["page_size"];
        /** @description Pagination token returned from the previous request */
        page_token?: components["parameters"]["page_token"];
        order_by?: components["parameters"]["order_by"];
        filter?: components["parameters"]["filter"];
      };
      header?: never;
      path: {
        chain: string;
        address: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DepositPage"];
        };
      };
    };
  };
  "list-withdrawals": {
    parameters: {
      query?: {
        order_by?: components["parameters"]["order_by"];
        filter?: components["parameters"]["filter"];
        /** @description Pagination token returned from the previous request */
        page_token?: components["parameters"]["page_token"];
        /** @description Amount of elements to return per page */
        page_size?: components["parameters"]["page_size"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WithdrawalPage"];
        };
      };
    };
  };
  "list-address-withdrawals": {
    parameters: {
      query?: {
        order_by?: components["parameters"]["order_by"];
        filter?: components["parameters"]["filter"];
        /** @description Pagination token returned from the previous request */
        page_token?: components["parameters"]["page_token"];
        /** @description Amount of elements to return per page */
        page_size?: components["parameters"]["page_size"];
      };
      header?: never;
      path: {
        chain: string;
        address: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WithdrawalPage"];
        };
      };
    };
  };
  "get-withdrawal": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        chain: string;
        hash: string;
        movement: string;
        withdrawal: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Withdrawal"];
        };
      };
    };
  };
  "list-movements": {
    parameters: {
      query?: {
        order_by?: components["parameters"]["order_by"];
        filter?: components["parameters"]["filter"];
        /** @description Pagination token returned from the previous request */
        page_token?: components["parameters"]["page_token"];
        /** @description Amount of elements to return per page */
        page_size?: components["parameters"]["page_size"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MovementPage"];
        };
      };
    };
  };
  "list-address-movements": {
    parameters: {
      query?: {
        order_by?: components["parameters"]["order_by"];
        filter?: components["parameters"]["filter"];
        /** @description Pagination token returned from the previous request */
        page_token?: components["parameters"]["page_token"];
        /** @description Amount of elements to return per page */
        page_size?: components["parameters"]["page_size"];
      };
      header?: never;
      path: {
        chain: string;
        address: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MovementPage"];
        };
      };
    };
  };
  "get-movement": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        chain: string;
        hash: string;
        movement: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Movement"];
        };
      };
    };
  };
  "get-ws-stream": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        stream: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      "2XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": (
            | components["schemas"]["Deposit"]
            | components["schemas"]["Withdrawal"]
            | components["schemas"]["Movement"]
          )[];
        };
      };
    };
  };
}
